"""entries table

Revision ID: 5f9a6b5f9e24
Revises: 7c1f4942a19d
Create Date: 2022-07-14 02:29:28.655935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a6b5f9e24'
down_revision = '7c1f4942a19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event__stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StageName', sa.String(length=64), nullable=False),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.Column('Location', sa.String(length=64), nullable=False),
    sa.Column('StageDate', sa.String(length=64), nullable=False),
    sa.Column('Qualifying', sa.Boolean(), nullable=False),
    sa.Column('PointsToQualify', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event__stage_Location'), 'event__stage', ['Location'], unique=False)
    op.create_index(op.f('ix_event__stage_StageDate'), 'event__stage', ['StageDate'], unique=False)
    op.create_index(op.f('ix_event__stage_StageName'), 'event__stage', ['StageName'], unique=False)
    op.drop_table('event_stage_results')
    op.drop_index('ix_event_stage_Location', table_name='event_stage')
    op.drop_index('ix_event_stage_StageDate', table_name='event_stage')
    op.drop_index('ix_event_stage_StageName', table_name='event_stage')
    op.drop_table('event_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_stage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('StageName', sa.VARCHAR(length=64), nullable=False),
    sa.Column('EventID', sa.INTEGER(), nullable=True),
    sa.Column('Location', sa.VARCHAR(length=64), nullable=False),
    sa.Column('StageDate', sa.VARCHAR(length=64), nullable=False),
    sa.Column('Qualifying', sa.BOOLEAN(), nullable=False),
    sa.Column('PointsToQualify', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_stage_StageName', 'event_stage', ['StageName'], unique=False)
    op.create_index('ix_event_stage_StageDate', 'event_stage', ['StageDate'], unique=False)
    op.create_index('ix_event_stage_Location', 'event_stage', ['Location'], unique=False)
    op.create_table('event_stage_results',
    sa.Column('ResultID', sa.INTEGER(), nullable=False),
    sa.Column('StageID', sa.INTEGER(), nullable=False),
    sa.Column('MemberID', sa.INTEGER(), nullable=False),
    sa.Column('PointsScored', sa.FLOAT(), nullable=False),
    sa.Column('Position', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['MemberID'], ['Members.MemberID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StageID'], ['event_stage.StageID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ResultID')
    )
    op.drop_index(op.f('ix_event__stage_StageName'), table_name='event__stage')
    op.drop_index(op.f('ix_event__stage_StageDate'), table_name='event__stage')
    op.drop_index(op.f('ix_event__stage_Location'), table_name='event__stage')
    op.drop_table('event__stage')
    # ### end Alembic commands ###
