"""entries table

Revision ID: 7c1f4942a19d
Revises: 
Create Date: 2022-07-14 00:11:52.226167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1f4942a19d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_description'), 'entry', ['description'], unique=False)
    op.create_index(op.f('ix_entry_title'), 'entry', ['title'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(length=64), nullable=False),
    sa.Column('Sport', sa.String(length=64), nullable=False),
    sa.Column('NZTeam', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_EventName'), 'events', ['EventName'], unique=False)
    op.create_index(op.f('ix_events_NZTeam'), 'events', ['NZTeam'], unique=False)
    op.create_index(op.f('ix_events_Sport'), 'events', ['Sport'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TeamName', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_TeamName'), 'teams', ['TeamName'], unique=False)
    op.create_table('event_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StageName', sa.String(length=64), nullable=False),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.Column('Location', sa.String(length=64), nullable=False),
    sa.Column('StageDate', sa.String(length=64), nullable=False),
    sa.Column('Qualifying', sa.Boolean(), nullable=False),
    sa.Column('PointsToQualify', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_stage_Location'), 'event_stage', ['Location'], unique=False)
    op.create_index(op.f('ix_event_stage_StageDate'), 'event_stage', ['StageDate'], unique=False)
    op.create_index(op.f('ix_event_stage_StageName'), 'event_stage', ['StageName'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TeamID', sa.Integer(), nullable=True),
    sa.Column('FirstName', sa.String(length=64), nullable=False),
    sa.Column('LastName', sa.String(length=64), nullable=False),
    sa.Column('City', sa.String(length=64), nullable=False),
    sa.Column('Birthdate', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['TeamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_Birthdate'), 'members', ['Birthdate'], unique=False)
    op.create_index(op.f('ix_members_City'), 'members', ['City'], unique=False)
    op.create_index(op.f('ix_members_FirstName'), 'members', ['FirstName'], unique=False)
    op.create_index(op.f('ix_members_LastName'), 'members', ['LastName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_LastName'), table_name='members')
    op.drop_index(op.f('ix_members_FirstName'), table_name='members')
    op.drop_index(op.f('ix_members_City'), table_name='members')
    op.drop_index(op.f('ix_members_Birthdate'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_event_stage_StageName'), table_name='event_stage')
    op.drop_index(op.f('ix_event_stage_StageDate'), table_name='event_stage')
    op.drop_index(op.f('ix_event_stage_Location'), table_name='event_stage')
    op.drop_table('event_stage')
    op.drop_index(op.f('ix_teams_TeamName'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_events_Sport'), table_name='events')
    op.drop_index(op.f('ix_events_NZTeam'), table_name='events')
    op.drop_index(op.f('ix_events_EventName'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entry_title'), table_name='entry')
    op.drop_index(op.f('ix_entry_description'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
